### ISSUE TITLE
Suggestions. 

### ISSUE THREAD

**Issue by gyke69** [DiscordDigital/ipax#10]
Disable extracting the app ICON was actually your idea in the previous issue which was created by someone else. but i am not sure are you making this change permanent so we wont be able to extract the icon from iPA files or it will be and false true.

1. currently ipax extracts , App icon . file name , bundleID , app name , version. could you add Enable/Disable option for these function so if we dont want ipax to extract file name we could just simply disable it. 
2. move PNG and json file to a customer folder.... i know your answer might be it is possible to do it with bash script , php etc etct. but it is just a suggestion so it might make ipax project way more complete. ( i remember that you said when it extracts data from ipa the ipax is locked there so it extracts all content in there.  

ps: if we make good changes and pull request do you merge it or you usually ignore them and add changes yourself? 

thank you.

**Comment by DiscordDigital** [comment]
Hi Anosh

About the suggestions:

1. I don't think it's in favor of speed or really anything to be able to disable elements inside the JSON output. However, it is planned that there'll be an option to disable the extraction and conversion of the PNG files, which will speed up the process of extraction.
2. I'll try to see if I can support custom folder locations within the virtual directory, this is planned for the next release.

About your ps: I only merge pull requests that I've agreed to and meet the standards of the project.

I'll work on these things when I've time.

Thank you for your patience

Best regards
DiscordDigital

**Comment by gyke69** [comment]
> Hi Anosh
> 
> About the suggestions:
> 
> 1. I don't think it's in favor of speed or really anything to be able to disable elements inside the JSON output. However, it is planned that there'll be an option to disable the extraction and conversion of the PNG files, which will speed up the process of extraction.
> 2. I'll try to see if I can support custom folder locations within the virtual directory, this is planned for the next release.
> 
> About your ps: I only merge pull requests that I've agreed to and meet the standards of the project.
> 
> I'll work on these things when I've time.
> 
> Thank you for your patience
> 
> Best regards DiscordDigital

Thank you!

**Comment by gyke69** [comment]
> Hi Anosh
> 
> About the suggestions:
> 
> 1. I don't think it's in favor of speed or really anything to be able to disable elements inside the JSON output. However, it is planned that there'll be an option to disable the extraction and conversion of the PNG files, which will speed up the process of extraction.
> 2. I'll try to see if I can support custom folder locations within the virtual directory, this is planned for the next release.
> 
> About your ps: I only merge pull requests that I've agreed to and meet the standards of the project.
> 
> I'll work on these things when I've time.
> 
> Thank you for your patience
> 
> Best regards DiscordDigital

could you add ipa size as well?

**Comment by DiscordDigital** [comment]
Hi Anosh

I've added a lot more features with version 1.2.

Can you test it out and let me know if everything's working like expected?

Thank you!

Best regards
DiscordDigital

**Comment by gyke69** [comment]
> Hi Anosh
> 
> I've added a lot more features with version 1.2.
> 
> Can you test it out and let me know if everything's working like expected?
> 
> Thank you!
> 
> Best regards DiscordDigital

Hello! and thank you it works pretty good.
