### ISSUE TITLE
a little problem. 

### ISSUE THREAD

**Issue by TheWastMajor** [DiscordDigital/ipax#14]
Traceback (most recent call last):
  File "/appdata/ipax.py", line 233, in <module>
    returnData = processIPA(
  File "/appdata/ipax.py", line 162, in processIPA
    extractAppIcon(ipaFullPath, iconNames, appicondir + "/" + newImageFileName)
  File "/appdata/ipax.py", line 113, in extractAppIcon
    shutil.move(max_file, '/home/work/files/' + SaveAs)
UnboundLocalError: local variable 'max_file' referenced before assignment

there are some ipa files i am getting this error only when i do multiple json and icon app at once, but if i extract 1 by one there is not error.

**Comment by DiscordDigital** [comment]
Hi TheWastMajor,

thanks for reaching out!

Can you please tell me what these IPA files are, and if I can legally obtain them?

It'd be helpful to me finding the issue, if you can look into these affected IPA files and find the difference to the other working IPA files, so maybe I can write a fix from this.

Thank you!

**Comment by TheWastMajor** [comment]
> Hi TheWastMajor,
> 
> thanks for reaching out!
> 
> Can you please tell me what these IPA files are, and if I can legally obtain them?
> 
> It'd be helpful to me finding the issue, if you can look into these affected IPA files and find the difference to the other working IPA files, so maybe I can write a fix from this.
> 
> Thank you!

I made those application using xcode, it seems that there are no issues with the ipa files because when i run ipax for a single first it works fine, sometimes it causes the issue when i run ipax for multiple files. for over the air i use [cfpropertylist] but i prefer ipax because it is fast and run through command line.

**Comment by DiscordDigital** [comment]
> > Hi TheWastMajor,
> > thanks for reaching out!
> > Can you please tell me what these IPA files are, and if I can legally obtain them?
> > It'd be helpful to me finding the issue, if you can look into these affected IPA files and find the difference to the other working IPA files, so maybe I can write a fix from this.
> > Thank you!
> 
> I made those application using xcode, it seems that there are no issues with the ipa files because when i run ipax for a single first it works fine, sometimes it causes the issue when i run ipax for multiple files. for over the air i use [cfpropertylist] but i prefer ipax because it is fast and run through command line.

Both single and multi-mode have been tested with many IPA files, it is interesting to know what's different on your files. Since you generate them yourself, can you create an empty IPA file which can be used to replicate this issue, so I can take a closer look at it?

**Comment by TheWastMajor** [comment]
> > > Hi TheWastMajor,
> > > thanks for reaching out!
> > > Can you please tell me what these IPA files are, and if I can legally obtain them?
> > > It'd be helpful to me finding the issue, if you can look into these affected IPA files and find the difference to the other working IPA files, so maybe I can write a fix from this.
> > > Thank you!
> > 
> > 
> > I made those application using xcode, it seems that there are no issues with the ipa files because when i run ipax for a single first it works fine, sometimes it causes the issue when i run ipax for multiple files. for over the air i use [cfpropertylist] but i prefer ipax because it is fast and run through command line.
> 
> Both single and multi-mode have been tested with many IPA files, it is interesting to know what's different on your files. Since you generate them yourself, can you create an empty IPA file which can be used to replicate this issue, so I can take a closer look at it?

Will do it once i have a chance.

**Comment by TheWastMajor** [comment]
The issue remains, just can't make time to share the files.
