### ISSUE TITLE
.png output! 

### ISSUE THREAD

**Issue by gyke69** [DiscordDigital/ipax#7]
if believe you touched something, 20 minute ago i created another server and build ipax. the png output is not accurate again. 
here is the screenshot:

https://ibb.co/8dH6mBd

the command i used.

docker run --rm -e multiple="true" -e outfile="result.json" -v '/home/world/Downloads/Telegram Desktop':/home/work/files ipax:latest

PS: why do i love this project? 
well since it is written in python it extracts the plist info plus png pretty fast.. with my current VPS i use another project from github it takes about 20 sec to extract png file from an ipa. meanwhile Ipax takes about 2-3 sec.. this project is the future.

**Comment by DiscordDigital** [comment]
Update 3:

Fixed 3 bugs in total:

1. Extended grabAppleXMLValue function to auto detect IPA files with single icons.
2. Added support for IPA files without icon.
3. Fixed a file cache bug which caused inconsistent icon results.

I also updated the files. Please clone the repository, build the image and test again.

Let me know if this worked or if there's still issues.

Thank you!

Best regards
DiscordDigital

**Comment by gyke69** [comment]
Dear DiscordDigital

here is the Update:
i have tried with my ubuntu OS which i use in daily basis , tried on 100+ ipa files! result is stable. 
tried on 2 VPS servers and the result is Stable. 

Thank you!
Ps: with the current stable update instead of md5 icon name isn't it possible to add the ipa name instead? or it will make it unstable again?

**Comment by DiscordDigital** [comment]
Hi Anosh

Glad to hear it's all working.

About the naming of the icons: 
I could consider it, however the md5 linking via JSON seems reasonable enough.
The md5 solution is also simpler and more stable because then I don't have to trim the extension of the filename.

I might change this behavior with a later update, if required, but for now I'll keep it like that.
You can fork and add this little change by yourself however, it should be fairly simple.

Best regards
DiscordDigital

**Comment by gyke69** [comment]
> Hi Anosh
> 
> Glad to hear it's all working.
> 
> About the naming of the icons: I could consider it, however the md5 linking via JSON seems reasonable enough. The md5 solution is also simpler and more stable because then I don't have to trim the extension of the filename.
> 
> I might change this behavior with a later update, if required, but for now I'll keep it like that. You can fork and add this little change by yourself however, it should be fairly simple.
> 
> Best regards DiscordDigital

Thanks for the quick answer! 
your answer is pretty reasonable! and i do not know anything about python since i am newbie.
