### ISSUE TITLE
Sort by list alphabetically.

### ISSUE THREAD

**Issue by gyke69** [DiscordDigital/ipax#8]
when sorting a json file the extract is randomly not alphabetically.
so if the file is a,b,c,d the json output is c,d,a,b.. kindly make it so it sorts in list according to first in each file alphabet. 

thanks in advance.
sorry for my weak English.

**Comment by DiscordDigital** [comment]
Hi Anosh

I added 3 new features of which one is sorting.
Can you clone the repository, and try it out?

I've updated the README file so you can see which parameters to add.
Please mind, the sorting only works when a default key is specified.

Best regards
DiscordDigital

**Comment by gyke69** [comment]
Dear DiscordDigital 
i just cloned and checked it this is the result. 
https://ibb.co/FHpfbww  , it works but it doesn't seem like it sorted alphabetically cause 'U" should be first then "Y"  
Example : Unc0ver then Youtube 

one more thing: 
could you add search by key,  "bundleId"  "filename" or "app name".. maybe not required but if it is possible add it as optional please. 

thanks

**Comment by gyke69** [comment]
> Hi
> 
> I don't know what your screenshot is from, but the sorting happens on the side of the client you're using. Please review the JSON output in case you have doubts about the sorting.
> 
> Also keep in mind the sort is case sensitive.
> 
> About the appname as key, I don't think that's necessary.
> 
> Best regards DiscordDigital

currently in my server side the both bundle ID and file name is pretty important while the app name isn't really important since were using apit to sort that app name out from apple.

**Comment by gyke69** [comment]
> Generally using the bundleId for anything is recommended, as app names can be duplicates and keynames can't exist twice in the same output. So it'd become a bit of an issue as soon as you have two versions of YouTube for example, when both use the same app name.

The bundles ID are changing randomly to com.api.$RANDOM

**Comment by DiscordDigital** [comment]
Why are the bundleIds randomized?

**Comment by gyke69** [comment]
> Why are the bundleIds randomized?

so people be able to keep their Origian application and duplicated one as well , and thats only possible if you change an app bundle ID otherwise it is not possible.

**Comment by DiscordDigital** [comment]
Well, then going by bundleId is still the better option. As I explained already, if the appname is present twice, it'll just overwrite the previous one. A key can only exist once with the same name.

**Comment by gyke69** [comment]
"bundleId" 
this option Actually deletes the bundle ID from .JSON file 
and if we use 'filename" it will delete the FileName From .JSON file.

**Comment by DiscordDigital** [comment]
The bundleId isn't gone actually, it's just present as the keyname.

You don't need the bundleId twice for example.

And you can also parse keynames from objects.

**Comment by DiscordDigital** [comment]
With overwrite I mean since keys can only exist once, as soon as there's another app with the same name, it'll overwrite the previous app. key-based values are only useful for things that can only exist once.

**Comment by gyke69** [comment]
https://diyorde.com/cdn/downloads/cert1/apps/apps.json

**Comment by DiscordDigital** [comment]
Please copy the contents into here, as I don't click external links

**Comment by gyke69** [comment]
{
    "Air Brush": {
        "AppName": "AirBrush CFire",
        "AppVersion": "4.22.0",
        "FileName": "AirBrush.ipa",
        "IconName": "03875750cfd4dbca901629f6da259b1c.png"
    },
    "Chimera": {
        "AppName": "Chimera",
        "AppVersion": "1.6.4",
        "FileName": "1.6.4-12.2-12.5.ipa",
        "IconName": "b832388e8f9606fae04e6c04f65d429e.png"
    },
    "ESign": {
        "AppName": "ESign",
        "AppVersion": "4.3.4",
        "FileName": "ESign_4.3.4_co_signed.ipa",
        "IconName": "66c2af6b0ad51c94a318d8e7105b89d2.png"
    },

**Comment by DiscordDigital** [comment]
Did you modify ipax to achieve this result?

**Comment by DiscordDigital** [comment]
The appname shouldn't be a key value, as it's not a unique value.

**Comment by gyke69** [comment]
> Did you modify ipax to achieve this result?

i did not touch aynthing, i just cloned and used that exact command, and in result the bundleid is gone... if i use "filename" the file name will be gone.

**Comment by DiscordDigital** [comment]
Give me a moment, I'll test it out on my files

**Comment by DiscordDigital** [comment]
The exact command resulted in a list of bundleIds as keynames for me.

**Comment by gyke69** [comment]
uhm seriously? let me remove ipax and clone it again.

**Comment by DiscordDigital** [comment]
Yeah it should look like this:
```
"com.rileytestut.GBA4iOS": {
        "AppName": "GBA4iOS",
        "AppVersion": "2.1",
        "FileName": "GBA4iOS.ipa",
        "IconName": "a565a234b3b904c26456b2e82b046c32.png"
}
```

**Comment by gyke69** [comment]
ah? and it doesn't have a vaule? possible to add a value in it?

**Comment by DiscordDigital** [comment]
What doesn't have a value?

**Comment by gyke69** [comment]
> What doesn't have a value?

wow i became a pain  in the neck haha!

**Comment by DiscordDigital** [comment]
When you need the bundleId to find the values, then why does the key need to be in the values again? You already have the bundleId at this point.

**Comment by DiscordDigital** [comment]
Can you try running ipax in single mode on an IPA like unc0ver? I don't understand how the appname ends up in your result, as I never added the appname as a key name.

**Comment by gyke69** [comment]
> When you need the bundleId to find the values, then why does the key need to be in the values again? You already have the bundleId at this point.

Dear DiscordDigital, iPax is using by at least 10 big " IRAN country " app store, they just django and php to made their store, into a json file there should be a value for everything base on json , otherwise the website cannot read weither the app/games is installed on your device or not.

**Comment by DiscordDigital** [comment]
You don't have to generate the list based on the key, if you don't use the defaultkey option, then it'll output like it did before. The defaultkey option is only useful when you want to filter for something like bundleId.

**Comment by DiscordDigital** [comment]
Appstores should be able to sort on their own. It's a very simple thing to do with JavaScript for example.

**Comment by gyke69** [comment]
root@vmi711011:~/ipax# docker run --rm -e filename="minecraft.ipa" -e defaultkey="bundleId" -e pretty="true" -v /home/diyorde/public_html/cdn/downloads/cert1/games/:/home/work/files ipax:latest

{
    "Minecraft": {
        "AppName": "Minecraft",
        "AppVersion": "1.16.10",
        "IconName": "30f8f439a01983cf134b8136bc3d5b04.png",
        "FileName": "minecraft.ipa"
    }
}

**Comment by gyke69** [comment]
sir! it is working. i figured there is something wrong with the ipa files somehow.

**Comment by gyke69** [comment]
the bundle ID without a value you made a disaster for me sir

**Comment by DiscordDigital** [comment]
You can still use the 1.0 release if you're unhappy with the changes. It's all on docker.io and GitHub.

**Comment by DiscordDigital** [comment]
Is there an open source IPA file which is affected by this issue? Then I can investigate what the issue is.

**Comment by gyke69** [comment]
> Is there an open source IPA file which is affected by this issue? Then I can investigate what the issue is.

i think i will use the older version of ipax at this point, i dont blame you i am not good at coding anything than css and html, so is my friends, we found the values pretty important in JSON.  and no there is no ipa affected by issue, the problems were with ipa files which i fixed it already and now it give me the output BundleID

**Comment by DiscordDigital** [comment]
Okay cool that it's working.

One more thing, if you run the same command without the new arguments, then it should behave like it did on the 1.0 version.

Can you confirm that?

```
docker run --rm -e filename="minecraft.ipa" -v /home/diyorde/public_html/cdn/downloads/cert1/games/:/home/work/files ipax:latest
```

**Comment by gyke69** [comment]
> Okay cool that it's working.
> 
> One more thing, if you run the same command without the new arguments, then it should behave like it did on the 1.0 version.
> 
> Can you confirm that?
> 
> ```
> docker run --rm -e filename="minecraft.ipa" -v /home/diyorde/public_html/cdn/downloads/cert1/games/:/home/work/files ipax:latest
> ```

yup! haha now i dont need to update i can use the current version with old commands which i used before... nice sir!

**Comment by gyke69** [comment]
Dear Digital! i forked it and hard coded it a bit, now my issue is fixed. thank you so much! with your update now the json result is clean, and works like a charm.
