### ISSUE TITLE
save time.

### ISSUE THREAD

**Issue by TheWastMajor** [DiscordDigital/ipax#9]
in order to save time and increase the process, you could possibly add if you dump json from multiple ipa and then add a new ipa, it should check if the previous ipas already exits it should re-dump them and it must dump the new ipa and add it into josn. same thing goes if an ipa is delete from that specific path it should delete the info from json. 

to make this process faster you could use the file name so it reads the file name and take action accordance.
add new ipa - if ipax.ipa is new add to json
delete ipa - if ipax.ipa is in json but doesn't exist in path delete it from json.

**Comment by DiscordDigital** [comment]
Hi TheWastMajor

To avoid further complexity and problems in the future this won't be added.
However feel free to fork this project and adjust the code to your needs.

If I were to make this possible I'd have to save the file hash in the result to check against.
While this might become an issue with hash-collision it can also result in a new issue with file size.

I wouldn't use the filename, as there might be a different app with the same name later on, this would be problematic.

ipax is currently fast enough.
I plan to add an optional flag which will disable the appicon generation, which probably speeds up the process as well.

Thank you for your suggestion!

Best regards
DiscordDigital

**Comment by gyke69** [comment]
> Hi TheWastMajor
> 
> 
> 
> To avoid further complexity and problems in the future this won't be added.
> 
> However feel free to fork this project and adjust the code to your needs.
> 
> 
> 
> If I were to make this possible I'd have to save the file hash in the result to check against.
> 
> While this might become an issue with hash-collision it can also result in a new issue with file size.
> 
> 
> 
> I wouldn't use the filename, as there might be a different app with the same filename later on, this would be problematic.
> 
> 
> 
> ipax is currently fast enough.
> 
> I plan to add an optional flag which will disable the appicon generation, which probably speeds up the process as well.
> 
> 
> 
> Thank you for your suggestion!
> 
> 
> 
> Best regards
> 
> DiscordDigital

Dear Digital! 
Pretty good! Suggestion in his case and I guess I am agree with what you said. 

I didn't really wanna open another issue but could you change -e keyword? For example we use -e almost for every Key! If you could change that it would become pretty clear. 😅

**Comment by DiscordDigital** [comment]
> 
> 
> > Hi TheWastMajor
> > To avoid further complexity and problems in the future this won't be added.
> > However feel free to fork this project and adjust the code to your needs.
> > If I were to make this possible I'd have to save the file hash in the result to check against.
> > While this might become an issue with hash-collision it can also result in a new issue with file size.
> > I wouldn't use the filename, as there might be a different app with the same filename later on, this would be problematic.
> > ipax is currently fast enough.
> > I plan to add an optional flag which will disable the appicon generation, which probably speeds up the process as well.
> > Thank you for your suggestion!
> > Best regards
> > DiscordDigital
> 
> Dear Digital! Pretty good! Suggestion in his case and I guess I am agree with what you said.
> 
> I didn't really wanna open another issue but could you change -e keyword? For example we use -e almost for every Key! If you could change that it would become pretty clear. 😅

Hi Anosh

Please open an issue when bringing up another topic.
Also unless you propose a different way to pass arguments into the container, it's not possible to change the "-e" keyword, as it's specific to how docker works.

Thank you

Best regards
DiscordDigital

**Comment by TheWastMajor** [comment]
> Hi TheWastMajor
> 
> To avoid further complexity and problems in the future this won't be added. However feel free to fork this project and adjust the code to your needs.
> 
> If I were to make this possible I'd have to save the file hash in the result to check against. While this might become an issue with hash-collision it can also result in a new issue with file size.
> 
> I wouldn't use the filename, as there might be a different app with the same filename later on, this would be problematic.
> 
> ipax is currently fast enough. I plan to add an optional flag which will disable the appicon generation, which probably speeds up the process as well.
> 
> Thank you for your suggestion!
> 
> Best regards DiscordDigital

two files cant be the same name anyways.
